name: Hexo Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup Hexo and render with Hexo
        run: |
          npm install hexo-cli -g
          npm install

      - name: Render with Hexo
        run: |
          hexo clean
          hexo generate

      - name: Setup SSH private key
        uses: webfactory/ssh-agent@v0.7.0
        with:
            ssh-private-key: ${{ secrets.HEXO_DEPLOY_KEY }}

      - name: Deploy to GitHub Pages
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_KEY }}
        run: |
          git config --global user.email "shhuluojia@github.com"
          git config --global user.name "billhu0"
          git clone git@github.com:billhu0/billhu0.github.io.git --depth=1
          cp -r billhu0.github.io/.git public/.git
          cd public
          git add --all
          git commit -m "Site updated"
          git push
          cd ..

