name: Hexo Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup Hexo and SSH key
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "shhuluojia@github.com"
          git config --global user.name "billhu0"
          npm install hexo-cli -g
          npm install

      - name: Hexo rendering 
        run: |
          hexo clean
          hexo generate

      - name: Deploy to GitHub Pages
        run: |
          git clone git@github.com:billhu0/billhu0.github.io.git --depth=1
          cp -r billhu0.github.io/.git public/.git
          cd public
          echo "z.billhu.cn" >> ./CNAME
          git add --all
          git commit -m "Site updated"
          git push
          rm -rf .git
          cd ..

      - name: Deploy to billhu.cn
        env: 
          BILLHU_CN_DEPLOY_KEY: ${{ secrets.BILLHU_CN_SSH_PRIVATE_KEY }}
        run: |
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan [101.43.107.49]:22112 >> ~/.ssh/known_hosts
          git clone ssh://ubuntu@101.43.107.49:22112/home/ubuntu/DocumentServer/Tool_docs/hexo_nginx/blog4.git --depth=1
          cp -r billhu0.github.io/.git blog4/.git
          cd blog4
          git add --all
          git commit -m "Site updated"
          git push
          rm -rf .git
          